<?php

// src/GanemosMadrid/PlenarioFormBundle/Entity/ParticipanteRepository.php

namespace GanemosMadridPlenarioFormBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ParticipanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipanteRepository extends EntityRepository
{

    public function getData()
    {
        $query = $this->createQueryBuilder('p')
                ->select('count(p), p.distrito')
                ->where('p.distrito != 22')
                ->groupBy('p.distrito')
                ->getQuery();


        try {
            $res = array();

            foreach ($query->getArrayResult() as $item) {
                $res[$item['distrito']] = $item[1];
            }
        } catch (\Doctrine\Orm\NoResultException $e) {
            $query = $this->createQueryBuilder('e')
                    ->orderBy('e.nombre', 'DESC')
                    ->setMaxResults(1)
                    ->getQuery();

            $res = $query->getSingleResult();
        }

        return $res;
    }

}
